# Check this on docker-compose doc
version: '3.7'

services:
      
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
        - postgres:/var/lib/postgresql/data
    networks:
      - sonarqube

  sonarqube:
    image: sonarqube:latest
    restart: always
    depends_on: 
      - postgres
    ports:
      - 9900:9000
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres/sonarqube
    volumes:
      - ./docker/sonarconf:/opt/sonarqube/conf
      - ./docker/sonardata:/opt/sonarqube/data
      - ./docker/sonarlogs:/opt/sonarqube/logs
      - ./docker/sonarext:/opt/sonarqube/extensions
    networks:
      - sonarqube

volumes:
  postgres:

networks:
  sonarqube:
    driver: bridge